#!/usr/bin/env bash
# The ablations of section 4.1, as runs rather than as remembered numbers.
#
#   bash code/ablations.sh            # build the derived reference sets, train, score
#
# Every arm is the orange at its own settings with exactly one thing changed, so each row of
# the tables it feeds is a difference and not a comparison between two pipelines. The control
# is the object's own run -- `orange` -- and is not retrained here; an arm that reproduces the
# control's settings would be a second sample of the control, which section 4.1.5 already
# reports separately.
#
# The derived reference sets are built by code/src/refset.py rather than by hand, because a
# directory someone assembled once is not a measurement that can be repeated. The rotated sets
# record the angle they injected, in rotation.json beside the photographs.
set -u
H=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
R=${FN_ROOT:?set FN_ROOT to the working tree}
PY=${FN_PY:?set FN_PY}
GPUS=${GPUS:-1 2 3}
LOGS=${LOGS:-$R/../logs}; mkdir -p "$LOGS"
cd "$R"

# --- the derived reference sets ------------------------------------------------------------
# Subsets first. "the first of each" and "the sixth of each" are two references, not two
# photographs of one plane: the interior is supervised by a transverse family and a
# longitudinal one, and an arm that dropped one family would be measuring something else.
sub () {  # sub NAME idx...
  local n=$1; shift
  [ -d "ablref_${n}_h" ] || $PY "$H/src/refset.py" subset secref_orraw_hsep "ablref_${n}_h" "$@"
  [ -d "ablref_${n}_v" ] || $PY "$H/src/refset.py" subset secref_orraw_vsep "ablref_${n}_v" "$@"
}
rot () {  # rot PSI
  local p=$1
  [ -d "ablref_rot${p}_h" ] || $PY "$H/src/refset.py" rotate secref_orraw_hsep "ablref_rot${p}_h" "$p" 0
  [ -d "ablref_rot${p}_v" ] || $PY "$H/src/refset.py" rotate secref_orraw_vsep "ablref_rot${p}_v" "$p" 1
}
sub n6 0 1 2 ; sub n2a 0 ; sub n2d 3 ; sub n2f 5
rot 5 ; rot 15 ; rot 30

# The single-level lattice: the same source at refine=1, so coarse and fine spacing are equal
# and the skin has no level of its own. This is what the released models were built on.
if [ ! -f build_orange_lvl1/lattice/gs_fill.ply ]; then
  echo "$(date -u +%H:%M:%S) building the single-level lattice"
  src=$(grep -m1 '^SRC=' "$H/objects/orange.conf" | cut -d= -f2- | sed 's/ *#.*//')
  dx=$(grep -m1 '^COARSE_DX=' "$H/objects/orange.conf" | cut -d= -f2- | sed 's/ *#.*//')
  CUDA_VISIBLE_DEVICES=1 $PY "$H/src/voxelize.py" "$src" build_orange_lvl1/lattice 1 0 "$dx" \
    > "$LOGS/lvl1.log" 2>&1
fi

# --- the arms ------------------------------------------------------------------------------
# name : conf overrides (blank for none) : environment
arms=(
  "abl_j0     ::JITTER=0"
  "abl_j025   ::JITTER=0.25"
  "abl_j1     ::JITTER=1"
  "abl_lvl1   ::LATTICE=build_orange_lvl1/lattice"
  "abl_rand   ::REF_RANDOM_ASSIGN=1"
  "abl_align  ::REF_PHASE_MODE=align"
  "abl_n6     :ablref_n6:"
  "abl_n2a    :ablref_n2a:"
  "abl_n2d    :ablref_n2d:"
  "abl_n2f    :ablref_n2f:"
  "abl_rot5   :ablref_rot5:"
  "abl_rot15  :ablref_rot15:"
  "abl_rot30  :ablref_rot30:"
)

set -- $GPUS; gpus=("$@"); ng=${#gpus[@]}; slot=0
for a in "${arms[@]}"; do
  name=$(echo "${a%%:*}" | tr -d ' ')
  rest=${a#*:}; refs=${rest%%:*}; envs=${rest#*:}
  conf="$H/objects/$name.conf"
  if [ ! -f "$conf" ]; then
    if [ -n "$refs" ]; then
      sed -e "s|^REF_H=.*|REF_H=${refs}_h|" -e "s|^REF_V=.*|REF_V=${refs}_v|" \
          "$H/objects/orange.conf" > "$conf"
    else
      cp "$H/objects/orange.conf" "$conf"
    fi
    sed -i "1i # ablation arm: $name. Generated by ablations.sh; the orange with one thing changed (${envs:-$refs})." "$conf"
  fi
  [ -f "$name/orange_demo_epoch_199.ply" ] && { echo "  $name done, skipping"; continue; }
  g=${gpus[$((slot % ng))]}; slot=$((slot+1))
  echo "$(date -u +%H:%M:%S) $name on gpu $g  ${envs:+[$envs]}${refs:+ refs=$refs}"
  env $envs GPU=$g nohup bash "$H/run.sh" "$name" > "$LOGS/$name.log" 2>&1 &
  while [ "$(jobs -r | wc -l)" -ge "$ng" ]; do sleep 30; done
done
wait
echo "$(date -u +%H:%M:%S) ABLATIONS_DONE"
for a in "${arms[@]}"; do
  n=$(echo "${a%%:*}" | tr -d ' ')
  printf "  %-11s %s\n" "$n" "$([ -f "$n/orange_demo_epoch_199.ply" ] && echo ok || echo MISSING)"
done
