#!/usr/bin/env bash
# The held-out study of section 4.1.2, as runs rather than as remembered numbers.
#
#   bash code/splits.sh
#
# Half of each family's photographs supervise the model and the other half are what it is
# scored against, so the number it reports is a distance to images the run never opened. The
# split is by alternating index -- even trains, odd is held out -- which spreads both halves
# through the depth range instead of giving training one end of the fruit and the evaluation
# the other.
#
# How many photographs a family holds decides which of two designs runs, and nothing else does:
#
#   four or more   one run, half against half.
#   three          three leave-one-out folds. Half of three leaves one image to score against,
#                  and a distance to a single photograph is a sample of one; the fold spread
#                  reported beside the mean is what says whether that mean means anything.
#   fewer          not run. There is nothing to hold out.
#
# An odd count gives the extra image to training, which is the conservative direction: it is
# the evaluation set that must not be flattered.
set -u
H=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
R=${FN_ROOT:?set FN_ROOT}; PY=${FN_PY:?set FN_PY}
GPUS=${GPUS:-1 2 3}; LOGS=${LOGS:-$R/../logs}; mkdir -p "$LOGS"
cd "$R"
conf () { grep -m1 "^$1=" "$H/objects/$2.conf" | cut -d= -f2- | sed 's/ *#.*//'; }
count () { $PY -c "
import sys; sys.path.insert(0,'$H/src')
from sds_demo import _photos_in
print(len(_photos_in('$1')))"; }

jobs_list=()
for o in orange watermelon apple bread cake pomegranate; do
  h=$(conf REF_H "$o"); v=$(conf REF_V "$o")
  n=$(count "$h"); m=$(count "$v")
  k=$(( n < m ? n : m ))
  echo "$o: $n transverse, $m longitudinal"
  if [ "$k" -ge 4 ]; then
    tr_i=$(seq 0 2 $((n-1)) | tr '\n' ' '); ho_i=$(seq 1 2 $((n-1)) | tr '\n' ' ')
    tv_i=$(seq 0 2 $((m-1)) | tr '\n' ' '); hv_i=$(seq 1 2 $((m-1)) | tr '\n' ' ')
    [ -d "spl_${o}_h" ] || $PY "$H/src/refset.py" subset "$h" "spl_${o}_h" $tr_i
    [ -d "spl_${o}_v" ] || $PY "$H/src/refset.py" subset "$v" "spl_${o}_v" $tv_i
    [ -d "hld_${o}_h" ] || $PY "$H/src/refset.py" subset "$h" "hld_${o}_h" $ho_i
    [ -d "hld_${o}_v" ] || $PY "$H/src/refset.py" subset "$v" "hld_${o}_v" $hv_i
    jobs_list+=("${o}_sp:spl_${o}")
  elif [ "$k" -eq 3 ]; then
    for i in 0 1 2; do
      tr_i=$(seq 0 2 | grep -v "^$i$" | tr '\n' ' ')
      [ -d "spl_${o}${i}_h" ] || $PY "$H/src/refset.py" subset "$h" "spl_${o}${i}_h" $tr_i
      [ -d "spl_${o}${i}_v" ] || $PY "$H/src/refset.py" subset "$v" "spl_${o}${i}_v" $tr_i
      [ -d "hld_${o}${i}_h" ] || $PY "$H/src/refset.py" subset "$h" "hld_${o}${i}_h" "$i"
      [ -d "hld_${o}${i}_v" ] || $PY "$H/src/refset.py" subset "$v" "hld_${o}${i}_v" "$i"
      jobs_list+=("${o}${i}_sp:spl_${o}${i}")
    done
  else
    echo "  too few to hold one out, not run"
  fi
done

set -- $GPUS; gpus=("$@"); ng=${#gpus[@]}; slot=0
for j in "${jobs_list[@]}"; do
  name=${j%%:*}; refs=${j#*:}
  base=$(echo "$name" | sed 's/[0-9]*_sp$//; s/_sp$//')
  conf_f="$H/objects/$name.conf"
  [ -f "$conf_f" ] || {
    sed -e "s|^REF_H=.*|REF_H=${refs}_h|" -e "s|^REF_V=.*|REF_V=${refs}_v|" \
        -e "s|^EVAL_REF=.*|EVAL_REF=${refs/spl_/hld_}_h|" \
        -e "s|^EVAL_REF_V=.*|EVAL_REF_V=${refs/spl_/hld_}_v|" \
        "$H/objects/$base.conf" > "$conf_f"
    sed -i "1i # held-out split of $base. Generated by splits.sh: the model sees ${refs}_*, and is scored against ${refs/spl_/hld_}_*, which it never opens." "$conf_f"
  }
  [ -f "$name/orange_demo_epoch_199.ply" ] && { echo "  $name done, skipping"; continue; }
  g=${gpus[$((slot % ng))]}; slot=$((slot+1))
  echo "$(date -u +%H:%M:%S) $name on gpu $g"
  GPU=$g nohup bash "$H/run.sh" "$name" > "$LOGS/$name.log" 2>&1 &
  while [ "$(jobs -r | wc -l)" -ge "$ng" ]; do sleep 30; done
done
wait
echo "$(date -u +%H:%M:%S) SPLITS_DONE"
for j in "${jobs_list[@]}"; do
  n=${j%%:*}; printf "  %-16s %s\n" "$n" "$([ -f "$n/orange_demo_epoch_199.ply" ] && echo ok || echo MISSING)"
done
